version: '3'

services:
  sredis:
    restart: always
    image: redis:alpine
    volumes:
      - redis-data:/data
      - "/etc/localtime:/etc/localtime:ro"
    command: --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "46379:6379"
    networks:
      - mynet

  spostgres:
    restart: always
    image: postgres:12.5
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - .envs/.local/.postgres
    ports:
      - "45432:5432"
    networks:
      - mynet


  sbackend:
    build:
      context: .
      dockerfile: .dockerfiles/sbackend.Dockerfile
    image: sbackend:${PROJECT_VERSION}
    restart: always
    volumes:
      - /var/log/sbackend:/var/log/sbackend
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - .envs/.local/.postgres
      - .envs/.local/.redis
    ports:
      - "40001:40001"
    depends_on:
      - sredis
      - spostgres
    networks:
      - mynet

  smgr:
    build:
      context: .
      dockerfile: .dockerfiles/smgr.Dockerfile
    image: smgr:${PROJECT_VERSION}
    restart: always
    env_file:
      - .envs/.local/.postgres
      - .envs/.local/.redis
    volumes:
      - /var/log/smgr:/var/log/smgr
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "40002:40002"
    depends_on:
      - sredis
      - spostgres
    networks:
      - mynet

  sworker1:
    build:
      context: .
      dockerfile: .dockerfiles/sworker.Dockerfile
    image: sworker:${PROJECT_VERSION}
    restart: always
    env_file:
      - .envs/.local/.postgres
      - .envs/.local/.redis
    environment:
      WORKER_INDEX: 1
    volumes:
      - /var/log/sworker1:/var/log/sworker
      - "/etc/localtime:/etc/localtime:ro"
    expose:
      - "40003"
    depends_on:
      - sredis
      - smgr
    networks:
      - mynet

  sworker2:
    build:
      context: .
      dockerfile: .dockerfiles/sworker.Dockerfile
    image: sworker:${PROJECT_VERSION}
    restart: always
    env_file:
      - .envs/.local/.postgres
      - .envs/.local/.redis
    environment:
      WORKER_INDEX: 2
    volumes:
      - /var/log/sworker2:/var/log/sworker
      - "/etc/localtime:/etc/localtime:ro"
    expose:
      - "40003"
    depends_on:
      - sredis
      - smgr
    networks:
      - mynet

networks:
  mynet:
    external: true
    name: scheduler_net

volumes:
  redis-data: {}
  postgres-data: {}

